sitewomen/sitewomen/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_page

from sitewomen import settings
from women.sitemaps import PostSitemap, CategorySitemap
from women.views import page_not_found
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    "posts": PostSitemap,
    "cats": CategorySitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("women.urls")),
    path("users/", include("users.urls", namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("captcha/", include("captcha.urls")),
    path(
        "sitemap.xml",
        cache_page(86400)(sitemap),
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Известные женщины мира"

sitewomen/users/urls.py
from django.contrib.auth.views import (
    LogoutView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path, reverse_lazy
from .views import LoginUser, RegisterUser, ProfileUser, UserPasswordChange

app_name = "users"

urlpatterns = [
    path("login/", LoginUser.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterUser.as_view(), name="register"),
    path("profile/", ProfileUser.as_view(), name="profile"),
    path("password-change/", UserPasswordChange.as_view(), name="password_change"),
    path(
        "password-change/done/",
        PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
        name="password_change_done",
    ),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

sitewomen/templates/base.html
{% load static %}
{% load women_tags %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'women/css/styles.css' %}">
    <link rel="shortcut icon" href="{% static 'women/images/main.ico' %}" type="image/x-icon">
</head>
<body>
    <div class="wrapper">
        <header class="header">
            <nav>
                <ul class="mainmenu">
                    <li class="logo"><a href="{% url 'home' %}"><div class="logo"></div></a></li>
                    {% for m in mainmenu %}
                    <li><a href="{% url m.url_name %}">{{ m.title }}</a></li>
                    {% endfor %}
                    {% if user.is_authenticated %}
                    <li class="last"><a href="{% url 'users:profile' %}">{{ user.username }}</a> | <a href="{% url 'users:logout' %}">Выйти</a></li>
                    {% else %}
                    <li class="last"><a href="{% url 'users:login' %}">Войти</a> | <a href="{% url 'users:register' %}">Регистрация</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>

        <div class="content-wrapper">
            <!-- Sidebar слева -->
            <aside class="left-chapters">
                <ul id="leftchapters">
                    {% if cat_selected == 0 %}
                    <li class="selected">Все категории</li>
                    {% else %}
                    <li><a href="{% url 'home' %}">Все категории</a></li>
                    {% endif %}
                    {% show_categories cat_selected %}
<!--                    <li class="share">-->
<!--                        <p>Наш канал</p>-->
<!--                        <a class="share-yt" href="https://www.youtube.com/channel/UClJzWfGWuGJL2t-3dYKcHTA/playlists" target="_blank" rel="nofollow"></a>-->
<!--                    </li>-->
                    <li>{% show_all_tags %}</li>
                </ul>
            </aside>
            <!-- Конец Sidebar'а -->

            <!-- Контент -->
            <main class="content">
                <!-- Хлебные крошки -->
                {% block breadcrumbs %}
                {% endblock %}

                <!-- Основной контент -->
                <div class="content-text">
                    {% block content %}
                    {% endblock %}
                </div>
                <!-- Конец основного контента -->

                <!-- Навигация -->
                {% block navigation %}
                {% endblock %}
            </main>
        </div>

        <!-- Footer -->
        <footer id="footer">
            <p>&copy; 2024 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
        </footer>
        <!-- Конец footer'а и страницы -->
    </div>
</body>
</html>